# file: k8s/web.yaml
apiVersion: v1
kind: ConfigMap # v1, wave 0
metadata:
  {
    name: web-config,
    namespace: demo,
    annotations: { argocd.argoproj.io/sync-wave: "0" },
  }
data: { MESSAGE: "hello from gitops" }
---
apiVersion: apps/v1
kind: Deployment # apps/v1, wave 1
metadata:
  {
    name: web,
    namespace: demo,
    annotations: { argocd.argoproj.io/sync-wave: "1" },
  }
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      {
        containers:
          [
            {
              name: web,
              image: nginx:1.27,
              envFrom: [{ configMapRef: { name: web-config } }],
            },
          ],
      }
---
apiVersion: v1
kind: Service # v1, wave 2
metadata:
  {
    name: web,
    namespace: demo,
    annotations: { argocd.argoproj.io/sync-wave: "2" },
  }
spec: { selector: { app: web }, ports: [{ port: 80, targetPort: 80 }] }
