apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            ruleNamespaceSelectorNilUsesHelmValues: false
        grafana:
          adminPassword: admin123
        alertmanager:
          config:
            global:
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: "${EMAIL}"
              smtp_auth_username: "${EMAIL}"
              smtp_auth_password: "${APP_PASSWORD}"
              smtp_require_tls: true

            route:
              receiver: email-personal
              group_by: ["alertname", "severity"]
              group_wait: 10s
              group_interval: 30s
              repeat_interval: 5m

            receivers:
              - name: email-personal
                email_configs:
                  - to: "${EMAIL}"
                    send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
